### ISSUE TITLE
System.Linq.Enumerable.First exception

### ISSUE THREAD

**Issue by ptrrssll** [ignatandrei/OneNoteOCR#5]
Got this exception using Chrome 74

Exception thrown: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OneNoteOCRDll.OneNoteOCR.FromImage(String imagePath)
   at OneNoteOCRDll.OneNoteOCR.RecognizeImage(String imagePath)

We take and log the screenshot with Pranas.ScreenshotCapture 1.0.11 and it appears to contain the correct text elements in a valid png file.

![Error_20190503103811_mod](https://user-images.githubusercontent.com/19260344/57116084-3c8e6e00-6d96-11e9-9e7f-59dc4a43ea03.png)

**Comment by ptrrssll** [comment]
Invalidoperationexception sequence contains no elements
Fixing LINQ Error: Sequence contains no elements. When you get theLINQ Error “Sequence contains no elements”, this is usually because you are using the First() or Single() command rather than FirstOrDefault() and SingleOrDefault().

https://stackoverflow.com/questions/11801769/handling-sequence-has-no-elements-exception

**Comment by ignatandrei** [comment]
Do you have the stack trace?
